module.exports = {
    roastList: [
      'YO MAMA IS SO UGLY THAT PEOPLE GO AS HER FOR HALLOWEEN.',
      'THE LAST TIME I SAW A FACE LIKE YOURS I FED IT A BANANA.',
      'I HEAR YOU ARE AN OFFICER. YOUR RANK IS - JUST PLAIN RANK!',
      'YO MAMA\'S NOSTRILS ARE SO HUGE SHE MAKES PATRICK EWING JEALOUS.',
      'YO MAMA IS SO GREASY THAT SHE\'S LABELED AS AN INGREDIENT IN CRISCO.',
      'ROSES ARE RED VIOLETS ARE BLUE, GOD MADE ME PRETTY, WHAT HAPPENED TO YOU?',
      'YO MAMA IS SO HAIRY THAT SHE HAS AFROS ON HER NIPPLES.',
      'ORDINARILY PEOPLE LIVE AND LEARN. YOU JUST LIVE.',
      'YO MAMA\'S SO NASTY, SHE WAS PLAYING IN A SAND BOX AND A CAT CAME ALONG AND BURIED HER.',
      'YO MAMA IS SO STUPID THAT SHE THOUGHT SHE NEEDED A TOKEN TO GET ON SOUL TRAIN.',
    ],
};